### ISSUE TITLE
 the current data update status in xronos

### ISSUE THREAD

**Issue by chmzs** [xronos-ch/xronos.R#10]
**Thank you for your great work and dedication.** 
Data should be dynamic. How can users know the current data update status in xronos? For example, the latest version of p3k14c data is 2022-06. Has it been included in xronos? Looking forward to your help~

**Comment by joeroe** [comment]
Hi @chmzs. As a quick answer: the latest (2022-06) version of p3k14c is included in XRONOS, yes. On your broader questions:

The data in XRONOS is dynamic and is updated continuously, not just when the source databases are updated; you can see this on individual records (e.g. https://xronos.ch/sites/12490#changelog shows a change I made last week) and behind-the-scenes we have a list of recent changes, which we should probably make public.

If someone wants to find out when we last imported a particular source database, we generally write a news post about major data imports (e.g. p3k14c is mentioned in https://xronos.ch/news/xronos-development-in-2022) so one option would be to look back through those – though I can see that this is not very convenient. We also list imported datasets at https://xronos.ch/about/acknowledgements (this may change in the future, as the list grows) and we should update this to include imported versions and dates.

Beyond that, source databases do not actually exist in our data model apart from as bibliographic references—that is, once something is imported into XRONOS, it is no longer explicitly tied to the source record—so I cannot see an obvious way to make this information more explicit. We're open to suggestions, though!
