### ISSUE TITLE
Error in chron_data(.everything = TRUE)

### ISSUE THREAD

**Issue by sweeney-l** [xronos-ch/xronos.R#5]
I'm getting the following error when I try and download the whole dataset. Filtering by individual countries works for some countries (e.g. Switzerland, Denmark) but I get the same error for others (e.g. France, Spain).

xronos_data <- xronos::chron_data(.everything = TRUE)
Error in `vctrs::data_frame()`:
! Can't recycle `id` (size 2) to match `typochronological_units` (size 3).
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/vctrs_error_incompatible_size>
Error in `vctrs::data_frame()`:
! Can't recycle `id` (size 2) to match `typochronological_units` (size 3).
---
Backtrace:
 1. xronos::chron_data(.everything = TRUE)
 2. xronos::xronos_request()
 3. xronos:::xronos_parse(response)
 4. purrr::map_dfr(result, "measurement")
 5. dplyr::bind_rows(res, .id = .id)
 6. dplyr:::map(...)
 7. base::lapply(.x, .f, ...)
 8. dplyr (local) FUN(X[[i]], ...)
 9. vctrs::data_frame(!!!.x, .name_repair = "minimal")
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/vctrs_error_incompatible_size>
Error in `vctrs::data_frame()`:
! Can't recycle `id` (size 2) to match `typochronological_units` (size 3).
---
Backtrace:
     ▆
  1. ├─xronos::chron_data(.everything = TRUE)
  2. │ └─xronos::xronos_request()
  3. │   └─xronos:::xronos_parse(response)
  4. │     └─purrr::map_dfr(result, "measurement")
  5. │       └─dplyr::bind_rows(res, .id = .id)
  6. │         └─dplyr:::map(...)
  7. │           └─base::lapply(.x, .f, ...)
  8. │             └─dplyr (local) FUN(X[[i]], ...)
  9. │               └─vctrs::data_frame(!!!.x, .name_repair = "minimal")
 10. └─vctrs::stop_incompatible_size(...)
 11.   └─vctrs:::stop_incompatible(...)
 12.     └─vctrs:::stop_vctrs(...)
 13.       └─rlang::abort(message, class = c(class, "vctrs_error"), ..., call = vctrs_error_call(call))

**Comment by MartinHinz** [comment]
Thanks for the report! You caught us between holidays and excavation (me) and extended family holidays (Joe). I'll see if I can find a quick solution, otherwise we'll take care of it asap, I promise.

**Comment by MartinHinz** [comment]
This issue goes deeper, it results from how site phases and respective typochronological and ecochronological units or phases are mapped in the api response. I commited a likely fix to xronos/xronos.rails, please, @joeroe, check if this is inline with your latest work on the data structure and the r-package and your future plans for both repos, whenever you find the time! Much appreciated!

**Comment by joeroe** [comment]
The Rails app's response is reasonable, I think, though it will change in the upcoming v2 API. The problem is more that the R package doesn't expect nested attributes like typochronological_unit. It didn't come up before because until https://github.com/xronos-ch/xronos.rails/commit/978ab39201bfcf3a0e9a68d086aa4b70bfc4ddd9, these simply weren't returned by the API.
